version: '3.8'

services:
  domaindrivenwebapplication.api:
    image: ${DOCKER_REGISTRY-}domaindrivenwebapplicationapi
    build:
      context: src/DomainDrivenWebApplication.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=SchoolDatabase;User Id=sa;Password=YourStr0ngP@ssw0rd!;TrustServerCertificate=true;
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStr0ngP@ssw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
