services:
  domaindrivenwebapplication.api:
    image: ${DOCKER_REGISTRY-}domaindrivenwebapplicationapi
    build:
      context: ..\
      dockerfile: docker\domaindrivenwebapplicationapi\Dockerfile
    container_name: domaindrivenwebapplication.api
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - mssql
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://0.0.0.0:8080;https://0.0.0.0:8081
      ASPNETCORE_HTTPS_PORT: 8081
    restart: unless-stopped

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "YourStr0ngP@ssw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge